import PDFDocument from "pdfkit";

export function generatePDFReport(scan) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
      
      doc.fontSize(24).fillColor("#1a1a2e").text("Social Media Exposure Report", { align: "center" });
      doc.moveDown();
      
      doc.fontSize(12).fillColor("#666").text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
      doc.moveDown(2);
      
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#ddd");
      doc.moveDown();
      
      doc.fontSize(16).fillColor("#1a1a2e").text("Profile Information");
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#333");
      doc.text(`Platform: ${scan.platform}`);
      doc.text(`Username: @${scan.username}`);
      doc.text(`Profile URL: ${scan.profileUrl}`);
      doc.moveDown();
      
      const riskColor = scan.riskLevel === "Critical" ? "#dc2626" : 
                       scan.riskLevel === "High" ? "#ea580c" :
                       scan.riskLevel === "Medium" ? "#ca8a04" : "#16a34a";
      
      doc.fontSize(16).fillColor("#1a1a2e").text("Risk Assessment");
      doc.moveDown(0.5);
      doc.fontSize(32).fillColor(riskColor).text(`${scan.riskScore}/100`, { continued: true });
      doc.fontSize(14).text(`  (${scan.riskLevel} Risk)`);
      doc.moveDown();
      
      doc.fontSize(16).fillColor("#1a1a2e").text("Findings Summary");
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#333");
      
      if (scan.findings.phones?.length > 0) {
        doc.text(`Phone Numbers Exposed: ${scan.findings.phones.length}`);
        scan.findings.phones.forEach((phone) => {
          doc.text(`  • ${phone}`, { indent: 20 });
        });
      }
      
      if (scan.findings.emails?.length > 0) {
        doc.text(`Email Addresses Exposed: ${scan.findings.emails.length}`);
        scan.findings.emails.forEach((email) => {
          doc.text(`  • ${email}`, { indent: 20 });
        });
      }
      
      doc.text(`Faces Detected: ${scan.findings.faces || 0}`);
      doc.text(`Location Data: ${scan.findings.gps || "None detected"}`);
      doc.moveDown();
      
      doc.fontSize(16).fillColor("#1a1a2e").text("Recommendations");
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor("#333");
      
      scan.recommendations?.forEach((rec, i) => {
        doc.text(`${i + 1}. ${rec}`);
      });
      
      doc.moveDown(2);
      doc.fontSize(9).fillColor("#999").text("This report was generated by Social Media Exposure Analyzer. The analysis is based on publicly available information.", { align: "center" });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
